---
- name: ngrok service
  become: yes
  copy:
    src: ngrok@.service
    dest: /lib/systemd/system/ngrok@.service
    mode: 0644 
    force: yes

- name: /opt/ngrok dir
  become: yes
  file:
    path: /opt/ngrok
    state: directory
    mode: 0755

- name: ngrok exe
  become: yes
  copy:
    src: ngrok
    dest: /opt/ngrok/ngrok
    mode: 0655
    force: yes

- name: create ngrok.conf
  become: true
  template: 
    src: ngrok.conf
    dest: /opt/ngrok/ngrok.conf
    force: yes

- name: ngrok systemd
  become: true
  systemd:
    name: ngrok@ssh.service
    state: started
    daemon_reload: yes
    enabled: true