# systemd-resolved
- name: disable systemd-resolved 
  systemd:
    name: systemd-resolved
    enabled: no
    state: stopped

- name: dnsmasq
  become: yes
  apt:
    name: dnsmasq
    state: present

- name: dnsmasq.conf
  become: yes
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: 0644 
    force: yes

- name: dnsmasq.conf
  become: yes
  template:
    src: dnsmasq_gfwlist_ipset.conf.j2
    dest: /etc/dnsmasq.d/dnsmasq_gfwlist_ipset.conf
    mode: 0644 
    force: yes

- name: dnsmasq service
  become: yes
  systemd:
    name: dnsmasq
    enabled: yes
    state: restarted    