---
# configure chinadns
- name: /opt/chinadns dir
  become: yes
  file:
    path: /opt/chinadns
    state: directory
    mode: 0755

- name: create chinadns
  become: true
  copy: 
    src: chinadns
    dest: /opt/chinadns/chinadns
    mode: 0555
    force: yes

- name: create chnroute file
  become: True
  copy:
    src:  chnroute.txt
    dest:  /opt/chinadns/chnroute.txt
    force: yes 
  
- name: create chinadns service
  become: true
  template:
    src: chinadns.service.j2
    dest: /lib/systemd/system/chinadns.service
    mode: 0644
    force: yes

 

- name: enable service chinadns.service 
  become: true
  systemd:
    name: chinadns
    enabled: yes
    daemon_reload: yes
    state: restarted




 